CREATE TABLE `game` (
	`id_game` INT(11) NOT NULL AUTO_INCREMENT,
	`name_game` CHAR(16) NOT NULL,
	`nbPlayer` TINYINT(1) NULL DEFAULT NULL,
	`pass_party` CHAR(16) NULL DEFAULT NULL,
	`creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`update` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`deroulement` TEXT NULL,
	PRIMARY KEY (`id_game`, `name_game`)
);
CREATE TABLE `party` (
	`id_party` INT(11) NOT NULL AUTO_INCREMENT,
	`id_game` INT(11) NULL DEFAULT NULL,
	`player` INT(11) NULL DEFAULT NULL,
	`id_player` TINYINT(3) NULL DEFAULT NULL,
	`hand` VARCHAR(13) NULL DEFAULT NULL,
	`creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_party`)
);
CREATE TABLE `player` (
	`id_player` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(16) NOT NULL,
	`pseudo` VARCHAR(16) NULL DEFAULT NULL,
	`pass_player` VARCHAR(16) NULL DEFAULT NULL,
	`email` VARCHAR(32) NOT NULL,
	`creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`update` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_player`, `name`, `email`)
);